session:
  size: 10
  timeout: 10
  concurrency_limit: 100

workers:
  num_workers: 1
  batch_size: 10

retry:
  max_retries: 1
  max_requests_per_session: 1

paths:
  wordlist: "../wordlists/names.txt"

session_init:
  url: "http://3cpo.hackingarena.com:801/"
